# Meta Data for SEO

## Homepage
title = "Possible Worlds"
titleSeparator = "-"
titleAddition = "AI for social innovation"
description = "At Possible Worlds, our mission is to build AI systems that support innovation in all corners of society."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["pw_logo_vertical.png"]
ogLocale = "en_US"
domainTLD = ""
titleHome = "Possible Worlds"

## Twitter Cards
twitterSite = "https://www.possible-world.xyz/"
twitterCreator = "Possible Worlds"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Possible Worlds"
schemaAuthor = "Possible Worlds"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = "https://www.linkedin.com/company/possibleworlds/"
schemaAuthorGitHub = ""
schemaLocale = "en-US"
schemaLogo = "pw_logo_vertical.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "pw_logo_vertical.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = "https://www.linkedin.com/company/possibleworlds/"
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>. Logo by <a class=\"text-muted\" href=\"https://leopalmerdesign.com/\">Leo Palmer</a>."

# Feed
copyRight = "Copyright (c) 2023 Possible Worlds"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing Possible Worlds. AI for social innovation."

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://www.possible-world.xyz/"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
